version: '3.7'

services:

  nginx-proxy:
    image: nginx
    volumes:
      - ./infraestructure/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - web
      - backend
  web:
    image: paconte/bookaslot-web:${BOOKASLOT_VERSION}
    environment:
      PROXY_API: http://backend:8000/
    depends_on:
      - backend

  backend:
    image: paconte/bookaslot-api:${BOOKASLOT_VERSION}
    restart: unless-stopped
    ports:
      - ${RESERVATIONS_API_PORT}:8000
    environment:
      DATABASE_URL: ${DOCKER_DATABASE_URL}
    depends_on:
      - postgres

  postgres:
    image: postgres:12.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${POSTGRES_DOCKER_VOLUME}
    logging:
      options:
        max-size: 10m
        max-file: "3"
