version: '3.7'

services:

  reservations-web:
    image: paconte/bookaslot-web:${BOOKASLOT_VERSION}
    #image: bookaslot-web
    environment:
      PROXY_API: http://reservations-api:8000/
    ports:
      - 5000:80
    depends_on:
      - reservations-api

  reservations-api:
    image: paconte/bookaslot-api:${BOOKASLOT_VERSION}
    #image: paconte/rs-reservation-api:${RESERVATIONS_API_VERSION}
    #image: rust-reservation-api
    restart: unless-stopped
    ports:
      - ${RESERVATIONS_API_PORT}:8000
    environment:
      DATABASE_URL: ${DOCKER_DATABASE_URL}
    depends_on:
      - postgres

  postgres:
    image: postgres:12.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${POSTGRES_DOCKER_VOLUME}
    logging:
      options:
        max-size: 10m
        max-file: "3"
