version: '3.7'

services:

  nginx-proxy:
    image: nginx
    volumes:
      - ./infraestructure/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - web
      - backend
  web:
    #container_name: bookaslot-web-dev
    build:
      context: ./web
      dockerfile: ./Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - ./web:/usr/src/app
      #- /usr/src/app/node_modules
    depends_on:
      - backend

  backend:
    image: bookaslot-api
    restart: unless-stopped
    ports:
      - ${RESERVATIONS_API_PORT}:8000
    environment:
      DATABASE_URL: ${DOCKER_DATABASE_URL}
    depends_on:
      - postgres

  postgres:
    image: postgres:12.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${POSTGRES_DOCKER_VOLUME}
    logging:
      options:
        max-size: 10m
        max-file: "3"
