FROM node:18-alpine3.15

WORKDIR /usr/src/app
COPY package.json package-lock.json rollup.config.js tailwind.config.js ./
RUN npm install && npm cache clean --force

COPY ./src ./src
COPY ./public ./public

#EXPOSE ${PORT}
EXPOSE 5000
ENV HOST=0.0.0.0

CMD ["npm", "run", "dev"]